"""Add admin user

Revision ID: 4a4b4bd09916
Revises: 7752ba0e01d1
Create Date: 2025-04-17 17:39:20.351234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from proj_name.core.crypto.passwords.base import PwdContext
from proj_name.models.auth.user import User
from proj_name.schemas.auth.user import UserCreate, UserRawCreate

# revision identifiers, used by Alembic.
revision: str = "4a4b4bd09916"
down_revision: Union[str, None] = "7752ba0e01d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ui = UserRawCreate(username="admin", password="admin", is_admin=True)
    user_data = UserCreate(
        password_hash=PwdContext.hash(ui.password),
        **ui.model_dump(exclude={"password"}),
    )
    op.execute(sa.insert(User).values(user_data.to_db()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.delete(User).where(User.username == "admin"))
    # ### end Alembic commands ###
